export const ADD_CAPABILITY = 'ADD_CAPABILITY';
export const UPDATE_CAPABILITY_DESCR = 'UPDATE_CAPABILITY_DESCR';
export const DELETE_CAPABILITY = 'DELETE_CAPABILITY';

export const UPDATE_SUPPORTED_API = 'UPDATE_SUPPORTED_API';
export const TOGGLE_AUTH_TYPE = 'TOGGLE_AUTH_TYPE';
export const UPDATE_AUTH_TYPE = 'UPDATE_AUTH_TYPE';

export const UPDATE_SINGLE_INPUT = 'UPDATE_SINGLE_INPUT';
export const UPDATE_FlAGS = 'UPDATE_FlAGS';
export const LOAD_FILE = 'LOAD_FILE';

export const ADD_CONF_SPEC = 'ADD_CONF_SPEC';
export const ADD_OPTIONS = 'ADD_OPTIONS';
export const DELETE_CONF_SPEC = 'DELETE_CONF_SPEC';
export const DELETE_ALL_OPTIONS = 'DELETE_ALL_OPTIONS';
export const DELETE_OPTION = 'DELETE_OPTION';
export const UPDATE_CONF_SPEC = 'UPDATE_CONF_SPEC';
export const UPDATE_OPTION = 'UPDATE_OPTION';

export const UPDATE_EXTERNAL_REFERENCE = 'UPDATE_EXTERNAL_REFERENCE';
export const ADD_EXTERNAL_REFERENCE = 'ADD_EXTERNAL_REFERENCE';
export const DELETE_EXTERNAL_REFERENCE = 'DELETE_EXTERNAL_REFERENCE';
