export const ADD_CAPABILITY = 'ADD_CAPABILITY';
export const UPDATE_CAPABILITY_DESCR = 'UPDATE_CAPABILITY_DESCR';
export const DELETE_CAPABILITY = 'DELETE_CAPABILITY';

export const UPDATE_SUPPORTED_API = 'UPDATE_SUPPORTED_API';

export const TOGGLE_AUTH_TYPE = 'UPDATE_AUTH_TYPE';

export const UPDATE_SINGLE_INPUT = 'UPDATE_SINGLE_INPUT';

export const UPDATE_FlAGS = 'UPDATE_FlAGS';

export const LOAD_FILE = 'LOAD_FILE';

export const ADD_CONF_SPEC = 'ADD_CONF_SPEC';



